# Generated by Django 2.2.10 on 2021-03-05 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banktransfers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_name', to='banktransfers.Customer')),
                ('to_field', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='to_name', to='banktransfers.Customer')),
            ],
        ),
    ]
