# Generated by Django 2.2.10 on 2021-03-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banktransfers', '0004_auto_20210309_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
